name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set env varr
      env:
        REACT_APP_GIT_SHA: GITHUB_SHA 
    - name: Run a multi-line script
      run: |
        yarn install && yarn deploy
        cd build/
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
